services:
  db:
    container_name: omega_backup
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=omegaBackup
      - MONGO_INITDB_ROOT_PASSWORD=1234
    ports:
      - 27017:27017
    expose:
      - 27017
